<%@ Page Language="C#" AutoEventWireup="true" CodeFile="view trains.aspx.cs" Inherits="admin_trains_Default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div class="grid1" style="text-align:center">
    
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" Caption="Trains" DataKeyNames="TrainNo" CellPadding="14" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" BackColor="White" BorderColor="#999999" BorderStyle="None" BorderWidth="1px" GridLines="Vertical">
            <AlternatingRowStyle BackColor="#DCDCDC" />
            <Columns>
                <asp:BoundField DataField="from" HeaderText="from" SortExpression="from" />
                <asp:BoundField DataField="To" HeaderText="To" SortExpression="To" />
                <asp:BoundField DataField="TrainNo" HeaderText="TrainNo" ReadOnly="True" SortExpression="TrainNo" />
                <asp:BoundField DataField="Dept" HeaderText="Dept" SortExpression="Dept" />
                <asp:BoundField DataField="Arri" HeaderText="Arri" SortExpression="Arri" />
                <asp:BoundField DataField="avail_SL" HeaderText="avail_SL" SortExpression="avail_SL" />
                <asp:BoundField DataField="avail_3A" HeaderText="avail_3A" SortExpression="avail_3A" />
                <asp:BoundField DataField="avail_2A" HeaderText="avail_2A" SortExpression="avail_2A" />
                <asp:BoundField DataField="avail_1A" HeaderText="avail_1A" SortExpression="avail_1A" />
                <asp:BoundField DataField="avail_CC" HeaderText="avail_CC" SortExpression="avail_CC" />
                <asp:BoundField DataField="avail_2S" HeaderText="avail_2S" SortExpression="avail_2S" />
                <asp:BoundField DataField="Type" HeaderText="Type" SortExpression="Type" />
                <asp:BoundField DataField="Quota" HeaderText="Quota" SortExpression="Quota" />
                <asp:BoundField DataField="Doj" HeaderText="Doj" SortExpression="Doj" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
            <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
            <SelectedRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#0000A9" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#000065" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:kioskConnectionString %>" SelectCommand="SELECT DISTINCT * FROM [trains_list]"></asp:SqlDataSource>
    
    </div>
    </form>
</body>
</html>
