<%@ Page Language="C#" AutoEventWireup="true" CodeFile="view_train Fares.aspx.cs" Inherits="admin_trains_view_train_Fares" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div class="grid1" style="text-align:center">

     
        <br />
        <br />
        <br />
&nbsp;<br />
&nbsp;<asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" HorizontalAlign="Center" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#E7E7FF" BorderStyle="None" BorderWidth="1px" CellPadding="10"   OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" Caption="TRAINS FARES">
            <AlternatingRowStyle BackColor="#F7F7F7" />
            <Columns>
                <asp:BoundField DataField="From"  HeaderText="From" SortExpression="From" />
                <asp:BoundField DataField="To" HeaderText="To" SortExpression="To" />
                <asp:BoundField DataField="Train No" HeaderText="Train No" SortExpression="Train No" />
                <asp:BoundField DataField="Class" HeaderText="Class" SortExpression="Class" />
                <asp:BoundField DataField="Quota" HeaderText="Quota" SortExpression="Quota" />
                <asp:BoundField DataField="Type" HeaderText="Type" SortExpression="Type" />
                <asp:BoundField DataField="Base Fare" HeaderText="Base Fare" SortExpression="Base Fare" />
                <asp:BoundField DataField="Reservation Charges" HeaderText="Reservation Charges" SortExpression="Reservation Charges" />
                <asp:BoundField DataField="Super Fast Charges" HeaderText="Super Fast Charges" SortExpression="Super Fast Charges" />
                <asp:BoundField DataField="Tatkal  Charges" HeaderText="Tatkal  Charges" SortExpression="Tatkal  Charges" />
                <asp:BoundField DataField="Total Fare" HeaderText="Total Fare" SortExpression="Total Fare" />
            </Columns>
            <FooterStyle BackColor="#B5C7DE" ForeColor="#4A3C8C" />
            <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#F7F7F7" />
            <PagerStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" HorizontalAlign="Right" />
            <RowStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" />
            <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="#F7F7F7" />
            <SortedAscendingCellStyle BackColor="#F4F4FD" />
            <SortedAscendingHeaderStyle BackColor="#5A4C9D" />
            <SortedDescendingCellStyle BackColor="#D8D8F0" />
            <SortedDescendingHeaderStyle BackColor="#3E3277" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:kioskConnectionString %>" SelectCommand="SELECT DISTINCT * FROM [train_fare_card]"></asp:SqlDataSource>

    </div>
    </form>
    </body>
</html>
