<%@ Page Language="C#" AutoEventWireup="true" CodeFile="view_airlines.aspx.cs" Inherits="admin_Airlines_view_airlines" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title> VIEW AIRLINES</title>
     <style type="text/css">
        .auto-style1 {
            text-align: center;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
   <div style="text-align:center">
    
        <div class="auto-style1">
            <br />
            <br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; LIST OF REGISTERED AIRLINES<br />
        <br />
        <br />
        <br />
        <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </div>
      
        <asp:GridView ID="GridView1" runat="server" CellPadding="10" AutoGenerateColumns="False" BackColor="White" BorderColor="White" BorderStyle="Ridge" BorderWidth="2px" Caption="AIRLINES" DataKeyNames="FlightNo" HorizontalAlign="Center" Width="10px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" CellSpacing="1" GridLines="None">  
                     
            <Columns>
                <asp:BoundField DataField="From" HeaderText="From" SortExpression="From" />
                <asp:BoundField DataField="To" HeaderText="To" SortExpression="To" />
                <asp:BoundField DataField="Economy_price" HeaderText="Economy_price" SortExpression="Economy_price" />
                <asp:BoundField DataField="Business_price" HeaderText="Business_price" SortExpression="Business_price" />
                <asp:BoundField DataField="FlightNo" HeaderText="FlightNo" ReadOnly="True" SortExpression="FlightNo" />
                <asp:BoundField DataField="Type" HeaderText="Type" SortExpression="Type" />
                <asp:BoundField DataField="Airlines" HeaderText="Airlines" SortExpression="Airlines" />
                <asp:BoundField DataField="via" HeaderText="via" SortExpression="via" />
                <asp:BoundField DataField="dept" HeaderText="dept" SortExpression="dept" />
                <asp:BoundField DataField="arri" HeaderText="arri" SortExpression="arri" />
                <asp:BoundField DataField="eco_avai" HeaderText="eco_avai" SortExpression="eco_avai" />
                <asp:BoundField DataField="bus_avai" HeaderText="bus_avai" SortExpression="bus_avai" />
            </Columns>
            <FooterStyle BackColor="#C6C3C6" ForeColor="Black" />
            <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#E7E7FF" />
            <PagerStyle BackColor="#C6C3C6" ForeColor="Black" HorizontalAlign="Right" />
            <RowStyle BackColor="#DEDFDE" ForeColor="Black" />
            <SelectedRowStyle BackColor="#9471DE" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#594B9C" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#33276A" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:kioskConnectionString %>" SelectCommand="SELECT DISTINCT * FROM [flights_list]"></asp:SqlDataSource>
&nbsp;
        </div>
    </form>
</body>
</html>
